### ISSUE TITLE
User tracks listing (even if not in a playlist)

### ISSUE THREAD

**Issue by gardie** [tobozo/oursophone#5]

**Comment by tobozo** [comment]
Agreed to show 'orphan' tracks.
How should this happen ? 
Clicking on a user will default to bringing back the playlists.
Clicking on the user search (glass magnifier icon) will also bring back the playlists.
-> add new button ?

**Comment by tobozo** [comment]
Re-using the glass-magnifier icon and allow ::alnum:: queries to also return tracklist :

https://github.com/tobozo/oursophone/blob/master/www/js/oursophone.js#L1102
