### ISSUE TITLE
Keep SC's HTML formatting in track and album description

### ISSUE THREAD

**Issue by gardie** [tobozo/oursophone#6]
would also be nice

**Comment by tobozo** [comment]
Will probably use JavaScript nl2br instead of css white-space:pre

    function nl2br (str, is_xhtml) {
        var breakTag = (is_xhtml || typeof is_xhtml === 'undefined') ? '<br />' : '<br>';
        return (str + '').replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g, '$1' + breakTag + '$2');
    }

**Comment by tobozo** [comment]
Fixed in commit https://github.com/tobozo/oursophone/commit/081227c563d1a11f81819c7c51e9ada4b8e1729e
